version: '3.5'

services:
  mongodb:
    container_name: iwow-mongodb
    image: mongo
    restart: always
    ports:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 7e3934K6Q47dN4PN

  api:
    container_name: iwow-api
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - mongodb

networks:
  default:
    name: iwow-network